somramnani/Moodsic

config/config.json
public/index.html
public/js/index.js
public/js/logic.js
public/styles/style.css

edited login page

---

.eslintrc.json
.travis.yml

Changed the YAML file so mysql is found.

updated yaml file for mysql

---

config/config.json

So this was a pointless change. Thanks.

changed config file but then I changed it back.

---

server.js

I started to add passport middleware but removed it because I want to make a more meaningful commit - nothing was changed on this commit.

no changes to code were made

---

models/user.js
server.js

Added the passport/sequelize user model to the project.

User model

---

.gitignore
public/js/logic.js
routes/apiRoutes.js

Added playback SDK code to client-side Logic.js

Playback sdk

---

public/js/spotify.js

Had commented out spotify.js for testing purposes , but now uncommented.

uncommented out spotify.js

---

public/js/auth.js
public/js/spotify.js
routes/apiRoutes.js

Added when the user signs in , it prints to the console the users email

 Added when the user signs in , it prints to the console the users email

---

package.json

deleted mocha

---

package-lock.json
package.json
public/index.html
public/styles/splash.css

updated font, added navbar delay time to match login, added account, fixed fluidity of splash

---

package-lock.json
package.json
public/styles/mobile.css
public/styles/mood.css

 edited mobile view on the login page

---

public/js/logic.js

For some reason, the linting website I used suggested that I change all the single quotes to double, so I went ahead and did it for logic.js

Changed all ' to " in logic.js, per lint

---

config/config.json
models/example.js

boilerplate sequelize model from models folder removed so it no longer loads when the server starts... also changed testdb to exampledb since we haven't created a testdb to load in test mode.

deleted example.js - updated config

---

public/account.html
public/index.html

need to connect all API routes, and make pages consistent

added account page w table to append users saved songs

---

public/js/logic.js

There are two variables in Logic.js that I'm unsure about. If someone could look at them and provide some guidance I'd really appreciate it. Thnx!!

Added comment on lines 52-53

---

.env
.gitignore

env is showing!!!!!!!!!!!!!!!!!!!!!

delted env

---

routes/htmlRoutes.js

Added }); at line 20 for the account page  in the htmlRoutes

}); in htmlRoutes

---

.env
public/index.html
routes/htmlRoutes.js

In the index.html file if the sourcing is like, "./public" with the '.' it doesnt work  so took out the '.'

Cleaned up, fixed the sourceing of the js

---

.env
routes/apiRoutes.js
routes/htmlRoutes.js
views/app.handlebars
views/testpage.handlebars

goes to main page instead of account page

Changed after login page direction

---

.env

URL change

---

.env
config/passport.js
routes/htmlRoutes.js
views/app.handlebars

Fixed the account page button goes to account page

Account page redirecting
